builds:
-
  main: ./cmd/capture
  id: capture
  binary: net.capture
  env:
    - CGO_ENABLED=1
    # experiments to compile godpi with nDPI module
#    - CC=/usr/local/Cellar/mingw-w64/7.0.0_1/bin/x86_64-w64-mingw32-gcc
#    - CXX=/usr/local/Cellar/mingw-w64/7.0.0_1/bin/x86_64-w64-mingw32-g++
#    - LDFLAGS="-L/usr/local/opt/libpcap/lib -L/usr/local/Cellar/liblinear/2.30/lib"
#    - CPPFLAGS="-I/usr/local/opt/libpcap/include -I/usr/local/Cellar/liblinear/2.30/include"
#    - PKG_CONFIG_PATH="/usr/local/opt/libpcap/lib/pkgconfig"

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    # - arm
    # - arm64
    # - 386
  
  # List of combinations of GOOS + GOARCH + GOARM to ignore.
  # Default is empty.
  # ignore:
  #   - goos: windows
  #     goarch: 386
  #   - goos: darwin
  #     goarch: 386
    # - goos: linux
    #   goarch: arm
    #   goarm: 7

  # Hooks can be used to customize the final binary,for example, to run generators.
  # Default is both hooks empty.
  # NETCAP uses a post hook to build the linux binaries in docker containers
  # and push the containers to the docker registry
  hooks:
    # this hook is used to compile the linux versions in a docker container
    post: zeus build-all-linux
    #pre: rice embed-go
-
  main: ./cmd/util
  id: util
  binary: net.util
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm
    - arm64
- 
  main: ./cmd/label
  id: label
  binary: net.label
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm
    - arm64
- 
  main: ./cmd/collect
  id: collect
  binary: net.collect
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm
    - arm64
- 
  main: ./cmd/agent
  id: agent
  binary: net.agent
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm
    - arm64
- 
  main: ./cmd/proxy
  id: proxy
  binary: net.proxy
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm
    - arm64
- 
  main: ./cmd/export
  id: export
  binary: net.export
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm
    - arm64
- 
  main: ./cmd/dump
  id: dump
  binary: net.dump
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm
    - arm64
## MALTEGO
## Plugins
#
-
  main: ./cmd/maltego/GetApplications
  id: GetApplications
  binary: GetApplications
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetDeviceContacts
  id: GetDeviceContacts
  binary: GetDeviceContacts
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetDeviceIPs
  id: GetDeviceIPs
  binary: GetDeviceIPs
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetDeviceProfiles
  id: GetDeviceProfiles
  binary: GetDeviceProfiles
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetDevices
  id: GetDevices
  binary: GetDevices
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetDNSQuestions
  id: GetDNSQuestions
  binary: GetDNSQuestions
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetDstPorts
  id: GetDstPorts
  binary: GetDstPorts
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetGeolocation
  id: GetGeolocation
  binary: GetGeolocation
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetHTTPContentTypes
  id: GetHTTPContentTypes
  binary: GetHTTPContentTypes
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetHTTPHosts
  id: GetHTTPHosts
  binary: GetHTTPHosts
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetHTTPServerNames
  id: GetHTTPServerNames
  binary: GetHTTPServerNames
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetHTTPStatusCodes
  id: GetHTTPStatusCodes
  binary: GetHTTPStatusCodes
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetHTTPURLs
  id: GetHTTPURLs
  binary: GetHTTPURLs
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetHTTPUserAgents
  id: GetHTTPUserAgents
  binary: GetHTTPUserAgents
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetSNIs
  id: GetSNIs
  binary: GetSNIs
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
-
  main: ./cmd/maltego/GetSrcPorts
  id: GetSrcPorts
  binary: GetSrcPorts
  env:
    - CGO_ENABLED=1

  # For more info refer to: https://golang.org/doc/install/source#environment
  goos:
    - darwin
    #- windows

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - -L /usr/local/opt/libpcap/lib -s -w

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64

brew:
  github:
    owner: dreadl0ck
    name: homebrew-formulas
  homepage: "https://github.com/dreadl0ck/netcap"
  description: "A framework for secure and scalable network traffic analysis"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

archives:
- 
  # Defaults are any files matching `LICENCE*`, `LICENSE*`,
  # `README*` and `CHANGELOG*` (case-insensitive).
  files:
    - LICENSE
    - README.md
    - types/cpp/*
    - types/csharp/*
    - types/java/*
    - types/js/*
    - types/python/*
    - types/rust/*
    - types/swift/*
    - types/netcap.pb.go

  format_overrides:
    - goos: windows
      format: zip

    # before:
#   hooks:
    # you may remove this if you don't use vgo
    #- go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...